### ISSUE TITLE
Instructions?

### ISSUE THREAD

**Issue by sweco-sekrsv** [CrashedBboy/blender-3d-tiler#1]
I have been looking for a 3D tiling tool and your repository looks like as a nice package. I would like to try it out.

Do you have any instructions on how to get it running?
Does it work with Blender 2.8 and maybe also 2.81?

**Comment by CrashedBboy** [comment]
Hello, I wrote these scripts with Blender 2.8, but I haven't try it on 2.81 yet.  

I think the python files in `scripts` directory may be the tools you are looking for,  
you can execute the code in Blender GUI text editor, or execute it in command line:  

```
blender -b -P script.py
```
