### ISSUE TITLE
i want convert gltf to 3d tiles,contains tileset.json and b3dm

### ISSUE THREAD

**Issue by dmff** [CrashedBboy/blender-3d-tiler#2]
how can i use blender-3d-tiler,i want convert gltf to 3d tiles,contains tileset.json and b3dm

**Comment by CrashedBboy** [comment]
Hi, please check `tiler_gltf.py` for the whole process.  
Additionally, you can use tool [3d-tiles-tools](https://www.npmjs.com/package/3d-tiles-tools) to convert GLB to B3DM (But the tileset.json needs to be calculated by yourself)

**Comment by dmff** [comment]
how can i calculated and create tileset.json? do you have this demo?

**Comment by CrashedBboy** [comment]
The steps of creating tileset.json are located in file `3dtiles-flat-generator.js` or `3dtiles-tree-generator.js`, which are used by the script `tiler_gltf.py`
